### ISSUE TITLE
Create pages from config file

### ISSUE THREAD

**Issue by Narno** [PHPoole/PHPoole-library#155]
Example:
```yaml
pages:
    - sitemap:
        - layout: sitemap.xml
        - permalink: sitemap.xml
    - 404:
        - title: Page non trouvée !
        - permalink: 404.html
    - rss:
        - layout: rss.xml
        - permalink: rss.xml
    - manifest:
        - layout: manifest
        - permalink: manifest.webmanifest
```
