### ISSUE TITLE
Multilingual support: content and templates translation

### ISSUE THREAD

**Issue by Narno** [PHPoole/PHPoole-library#177]
## Templates

https://github.com/twigphp/Twig-extensions/blob/master/doc/i18n.rst

```twig
{% trans "Hello World!" %}

{% trans %}
    Hello {{ name }}!
{% endtrans %}
```

## Content

Config:
```yaml
site:
    title: My amazing Website!
languages:
    fr:
        site:
            title: Mon incroyable site Web !
```

Files:
* `about.md`
* `about.fr.md`
