### ISSUE TITLE
Generator: Sitemap

### ISSUE THREAD

**Issue by Narno** [PHPoole/PHPoole-library#178]
Create a global (all pages) sitemap page with:
- id = `sitemap`
- layout = `sitemap.xml` (internal layout `sitemap.xml.twig`)

Add options in configuration:
```
site:
    sitemap:
        disable: false
        exclude: ['sitemap', '404', 'rss', 'manifest']
```
