### ISSUE TITLE
Generator: RSS

### ISSUE THREAD

**Issue by Narno** [PHPoole/PHPoole-library#179]
Create a RSS page

A global (all pages) with:
- id = `sitemap`
- layout = `rss.xml` (internal layout `rss.xml.twig`)

By section with:
- id = `SECTION-sitemap`
- layout = `section.rss.xml` (internal layout `section.rss.xml.twig`)

Add options in configuration:
```yaml
site:
    rss:
        disable: false
        exclude: ['sitemap', '404', 'rss', 'manifest']
        bysection: true
        byterm:true
```
